matrix:
  VERSION:
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay --graph /drone/docker &
    - sleep 2
    - docker build --tag build-image-temp --file $$VERSION/Dockerfile.build $$VERSION
    - docker run --rm --volume $PWD/$$VERSION:/target build-image-temp

publish:
  hub_filebeat_master:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/Dockerfile-filebeat"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/filebeat
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

  hub_topbeat_master:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/Dockerfile-topbeat"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/topbeat
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

  hub_packetbeat_master:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/Dockerfile-packetbeat"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/packetbeat
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
