FROM armhfbuild/alpine:3.3

RUN apk --update-cache add ca-certificates libpcap
COPY ./packetbeat /usr/bin/
COPY ./packetbeat.yml /etc/packetbeat/

CMD ["packetbeat", "-e", "-c=/etc/packetbeat/packetbeat.yml"]
