FROM armhfbuild/debian

RUN apt-get update && apt-get install libpcap0.8
COPY ./packetbeat /usr/local/bin/
COPY ./packetbeat.yml /etc/packetbeat/

CMD ["packetbeat", "-e", "-c=/etc/packetbeat/packetbeat.yml"]
